/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package breadman.vista.admin.paneles.inventario;
import breadman.logica.modelo.entidades.Insumo;
import breadman.logica.modelo.persistencia.daos.ControlInsumo;
import breadman.logica.modelo.util.FactoryColumnModel;
import breadman.logica.modelo.util.TableModelData;
import breadman.logica.modelo.util.graficas.FactoryChart;
import breadman.logica.modelo.util.graficas.TipoGrafica;
import breadman.vista.MainPanel;
import breadman.vista.SwingAttribute;
import org.jfree.chart.ChartPanel;
/**
 *
 * @author Ariel Arnedo
 */
public class PanelInventarioInsumo extends MainPanel {
    
    /**
     * Creates new form PanelInventarioInsumo
     */
    public PanelInventarioInsumo() {
        super();
        initComponents();
        updatePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelInsumoTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInsumos = new javax.swing.JTable();
        panelInsumoChart = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        panelInsumoTable.setBorder(SwingAttribute.BORDER_SECUNDARY);
        panelInsumoTable.setPreferredSize(new java.awt.Dimension(0, 0));
        panelInsumoTable.setLayout(new java.awt.BorderLayout());

        tableInsumos.setModel(new TableModelData(Insumo.class)
        );
        tableInsumos.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(tableInsumos);
        tableInsumos.setColumnModel(FactoryColumnModel.createModelColumnTableInsumo());

        panelInsumoTable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        add(panelInsumoTable, gridBagConstraints);

        panelInsumoChart.setBorder(SwingAttribute.BORDER_SECUNDARY);
        panelInsumoChart.setPreferredSize(new java.awt.Dimension(0, 0));
        panelInsumoChart.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        add(panelInsumoChart, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void updatePanels(){
        panelInsumoChart.add(new ChartPanel(FactoryChart.createPanelChartBar(TipoGrafica.COMPRA_INSUMO_POR_DIA)));
        TableModelData tableModelData = (TableModelData) tableInsumos.getModel();
        tableModelData.add(new ControlInsumo().listarTodas(), Insumo.class);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelInsumoChart;
    private javax.swing.JPanel panelInsumoTable;
    private javax.swing.JTable tableInsumos;
    // End of variables declaration//GEN-END:variables
}
