/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package breadman.vista.admin.paneles.vendedor;

import breadman.logica.modelo.entidades.Vendedor;
import breadman.logica.modelo.persistencia.daos.ControlVendedor;
import breadman.logica.modelo.util.ComboBoxModelo;
import breadman.logica.modelo.util.FactoryCellListRenderer;
import breadman.logica.modelo.util.FactoryColumnModel;
import breadman.logica.modelo.util.TableModelData;
import breadman.logica.modelo.util.TipoDato;
import breadman.logica.modelo.util.graficas.FactoryChart;
import breadman.logica.modelo.util.graficas.TipoGrafica;
import breadman.vista.MainPanel;
import breadman.vista.SwingAttribute;


import org.jfree.chart.ChartPanel;
/**
 *
 * @author Ariel Arnedo
 */
public class PanelAdminVendedor extends MainPanel {
    
    
    /**
     * Creates new form PanelDataVendedor
     */
    public PanelAdminVendedor() {
        super();
        initComponents();
        updatePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelMoreSellVendedor = new javax.swing.JPanel();
        panelDataChartSell = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSalesPerVendedor = new javax.swing.JTable();
        panelDataVendedor = new javax.swing.JPanel();
        panelSeleccionVendedor = new javax.swing.JPanel();
        comboBoxVendedores = new javax.swing.JComboBox<>();
        panelTrabajo = new javax.swing.JPanel();
        panelVentaPorDia = new javax.swing.JPanel();
        panelFlowVenta = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        panelMoreSellVendedor.setBorder(SwingAttribute.BORDER_SECUNDARY);
        panelMoreSellVendedor.setPreferredSize(new java.awt.Dimension(0, 0));
        panelMoreSellVendedor.setLayout(new java.awt.GridBagLayout());

        panelDataChartSell.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelMoreSellVendedor.add(panelDataChartSell, gridBagConstraints);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tableSalesPerVendedor.setModel(new TableModelData(TableModelData.DataSalesMoreProduct.class)
        );
        tableSalesPerVendedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tableSalesPerVendedor);
        tableSalesPerVendedor.setColumnModel(FactoryColumnModel.createModelColumnTableSales());

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
        panelMoreSellVendedor.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 5);
        add(panelMoreSellVendedor, gridBagConstraints);

        panelDataVendedor.setBorder(SwingAttribute.BORDER_SECUNDARY);
        panelDataVendedor.setName(""); // NOI18N
        panelDataVendedor.setPreferredSize(new java.awt.Dimension(0, 0));
        panelDataVendedor.setVerifyInputWhenFocusTarget(false);
        panelDataVendedor.setLayout(new java.awt.BorderLayout());

        panelSeleccionVendedor.setLayout(new java.awt.BorderLayout());

        comboBoxVendedores.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comboBoxVendedores.setModel(new ComboBoxModelo(TipoDato.VENDEDORES));
        comboBoxVendedores.setSelectedIndex(0);
        comboBoxVendedores.setRenderer(FactoryCellListRenderer.createListCellRendererComboBox());
        comboBoxVendedores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxVendedoresItemStateChanged(evt);
            }
        });
        panelSeleccionVendedor.add(comboBoxVendedores, java.awt.BorderLayout.CENTER);

        panelDataVendedor.add(panelSeleccionVendedor, java.awt.BorderLayout.NORTH);

        panelTrabajo.setLayout(new java.awt.GridBagLayout());

        panelVentaPorDia.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        panelTrabajo.add(panelVentaPorDia, gridBagConstraints);

        panelFlowVenta.setPreferredSize(new java.awt.Dimension(0, 0));
        panelFlowVenta.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        panelTrabajo.add(panelFlowVenta, gridBagConstraints);

        panelDataVendedor.add(panelTrabajo, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        add(panelDataVendedor, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxVendedoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxVendedoresItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            Vendedor vendedor = (Vendedor) comboBoxVendedores.getSelectedItem();
            panelVentaPorDia.removeAll();
            panelVentaPorDia.add(new ChartPanel(FactoryChart.createPanelChartBar(vendedor, TipoGrafica.VENTAS_DIARIAS_POR_VENDEROR)));
            panelVentaPorDia.updateUI();
        }
    }//GEN-LAST:event_comboBoxVendedoresItemStateChanged


    private void updatePanels(){
        panelDataChartSell.add(new ChartPanel(FactoryChart.createPanelChartBar(TipoGrafica.VENTAS_POR_VENDEDOR)));
        panelFlowVenta.add(new ChartPanel(FactoryChart.createPanelSerieTimeChart(TipoGrafica.VENTAS_POR_TIEMPO_AND_VENDEDOR)));
        TableModelData tableModelData = (TableModelData) tableSalesPerVendedor.getModel();
        tableModelData.add(new ControlVendedor().getMayorVentaPorVendedor(),TableModelData.DataSalesMoreProduct.class);
        
        if(comboBoxVendedores.getModel().getSize() != 0){
            ComboBoxModelo comboBoxModelo = (ComboBoxModelo) comboBoxVendedores.getModel();
            Vendedor vendedor = (Vendedor) comboBoxModelo.getElementAt(0);
            panelVentaPorDia.add(new ChartPanel(FactoryChart.createPanelChartBar(vendedor, TipoGrafica.VENTAS_DIARIAS_POR_VENDEROR)));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxVendedores;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDataChartSell;
    private javax.swing.JPanel panelDataVendedor;
    private javax.swing.JPanel panelFlowVenta;
    private javax.swing.JPanel panelMoreSellVendedor;
    private javax.swing.JPanel panelSeleccionVendedor;
    private javax.swing.JPanel panelTrabajo;
    private javax.swing.JPanel panelVentaPorDia;
    private javax.swing.JTable tableSalesPerVendedor;
    // End of variables declaration//GEN-END:variables
}
