/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package breadman.vista.venta;

import breadman.logica.modelo.core.ControlUserModel;
import breadman.logica.modelo.entidades.Categoria;
import breadman.logica.modelo.entidades.Inventario;
import breadman.logica.modelo.entidades.Producto;
import breadman.logica.modelo.entidades.Venta;
import breadman.logica.modelo.persistencia.VentaJpaController;
import breadman.logica.modelo.persistencia.daos.ControlCategoria;
import breadman.logica.modelo.persistencia.daos.ControlInventario;
import breadman.logica.modelo.persistencia.daos.ControlVenta;
import breadman.logica.modelo.util.ComboBoxModelo;

import breadman.logica.modelo.util.FactoryColumnModel;
import breadman.logica.modelo.util.FactoryCellListRenderer;
import breadman.logica.modelo.util.TableModelData;
import breadman.logica.modelo.util.TipoDato;
import breadman.vista.MainFrame;
import breadman.vista.SwingAttribute;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Ariel Arnedo
 */
public class FrameVenta extends MainFrame {

   
    
    public FrameVenta() {
        super("VENTAS - "+ControlUserModel.getInstance().getUsuario().getNombre());
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBoxCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        botonRegisrtrarCompra = createButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = createLabelSecundary();
        jSeparator2 = new javax.swing.JSeparator();
        labelTotalCompra = createLabel();
        jLabel6 = createLabelSecundary();
        campoCantidad = createTextFieldNumeric();
        jLabel7 = createLabelSecundary();
        labelPrecio = createLabel();
        botonAñadirProducto = createButtonSecondary();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        botonCancelar = createButton();
        jLabel2 = createLabelPrimary();
        jLabel3 = createLabelPrimary();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        comboBoxCategoria.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comboBoxCategoria.setModel(new ComboBoxModelo(TipoDato.CATEGORIAS));
        comboBoxCategoria.setSelectedIndex(0);
        comboBoxCategoria.setBorder(SwingAttribute.BORDER_MAIN);
        comboBoxCategoria.setRenderer(FactoryCellListRenderer.createListCellRendererComboBox());
        comboBoxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxCategoriaItemStateChanged(evt);
            }
        });
        comboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCategoriaActionPerformed(evt);
            }
        });

        listaProductos.setBorder(SwingAttribute.BORDER_MAIN);
        listaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaProductos.setCellRenderer(FactoryCellListRenderer.createListCellRenderer());
        jScrollPane1.setViewportView(listaProductos);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));

        botonRegisrtrarCompra.setText("Registrar Compra");
        botonRegisrtrarCompra.setEnabled(false);
        botonRegisrtrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegisrtrarCompraActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Total:");

        labelTotalCompra.setText("$ 0");

        jLabel6.setText("Cantidad");

        campoCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCantidadKeyReleased(evt);
            }
        });

        jLabel7.setText("Precio");

        labelPrecio.setText("$ 0");

        botonAñadirProducto.setText("AÃ±adir");
        botonAñadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	botonAñdirProductoActionPerformed(evt);
            }
        });

        jPanel4.setLayout(new java.awt.BorderLayout());

        tablaProductos.setModel(new TableModelData(TableModelData.DataRegisterSell.class));
        jScrollPane2.setViewportView(tablaProductos);
        tablaProductos.setColumnModel(FactoryColumnModel.createModelColumnTableProducts());

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(botonAñadirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonRegisrtrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAñadirProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelTotalCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegisrtrarCompra)
                    .addComponent(botonCancelar))
                .addGap(15, 15, 15))
        );

        jLabel2.setText("Categorias");

        jLabel3.setText("Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxCategoriaItemStateChanged
        
    }//GEN-LAST:event_comboBoxCategoriaItemStateChanged

    private void comboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCategoriaActionPerformed
       if (comboBoxCategoria.getItemCount() > 0) {
            Categoria categoria = (Categoria) comboBoxCategoria.getSelectedItem();
            listaProductos.setModel(new ComboBoxModelo(categoria.getProductoList()));
       }
    }//GEN-LAST:event_comboBoxCategoriaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (comboBoxCategoria.getItemCount() > 0) {
            Categoria categoria = (Categoria) comboBoxCategoria.getSelectedItem();
            listaProductos.setModel(new ComboBoxModelo(categoria.getProductoList()));
        } 
    }//GEN-LAST:event_formWindowOpened

    private void campoCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCantidadKeyReleased
        if(!listaProductos.isSelectionEmpty()){
            if(!isFieldEmply(campoCantidad)){
                 Integer cantidad = Integer.parseInt(campoCantidad.getText());
                 ComboBoxModelo comboBoxModelo = (ComboBoxModelo) listaProductos.getModel();
                 Producto producto = (Producto) comboBoxModelo.getElementAt(listaProductos.getSelectedIndex());
                 labelPrecio.setText("$ " + producto.getPrecioDeVenta()* cantidad);
           }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccione un producto primero");
            campoCantidad.setText("");
        }
    }//GEN-LAST:event_campoCantidadKeyReleased

    private void botonAñdirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAÃ±adirProductoActionPerformed
        if(!listaProductos.isSelectionEmpty()){
            if(!isFieldEmply(campoCantidad)){
                 Integer cantidad = Integer.parseInt(campoCantidad.getText());
                 ComboBoxModelo comboBoxModelo = (ComboBoxModelo) listaProductos.getModel();
                 Producto producto = (Producto) comboBoxModelo.getElementAt(listaProductos.getSelectedIndex());
                 
                 Inventario inventario = new ControlInventario().getInventario(producto);
                 
                 if(inventario != null){
                     if(inventario.getCantidad() < cantidad){
                         JOptionPane.showMessageDialog(rootPane, "Â¡Uoops! Noy hay suficiente " + producto.getNombre() +" para esta compra");
                     }else{
                         TableModelData tableModelData = (TableModelData) tablaProductos.getModel();
                         boolean add = tableModelData.add(new TableModelData.DataRegisterSell(producto, cantidad));
                         labelTotalCompra.setText("$ " + tableModelData.getCantPrimary());
                         if(!add){
                             JOptionPane.showMessageDialog(rootPane, "Â¡Uoops! Producto no fuÃ© aÃ±adido a la lista de compras\nIntentelo una vez mÃ¡s");
                             botonRegisrtrarCompra.setEnabled(false);
                         }else{
                             botonRegisrtrarCompra.setEnabled(true);
                         }
                     }
                 }else{
                     JOptionPane.showMessageDialog(rootPane, "Â¡Uoops! El producto aun no esta en inventario");
                     botonRegisrtrarCompra.setEnabled(false);
                 }
           }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccione un producto primero");
            campoCantidad.setText("");
            botonRegisrtrarCompra.setEnabled(false);
        }
    }//GEN-LAST:event_botonAÃ±adirProductoActionPerformed

    private void botonRegisrtrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegisrtrarCompraActionPerformed
        List list =  ((TableModelData) tablaProductos.getModel()).getData();
        List<Venta> ventas = new ArrayList<>();
        list.stream().map((object) -> (TableModelData.DataRegisterSell)object).forEachOrdered((data) -> {
            Venta venta = new Venta();
            venta.setCantidadComprada(((TableModelData.DataRegisterSell)data).getCantidad());
            venta.setValorCompra((float)(((TableModelData.DataRegisterSell)data).getCantidad()*((TableModelData.DataRegisterSell)data).getProducto().getPrecioDeVenta()));
            venta.setFechaDeCompra(new java.sql.Date(new GregorianCalendar().getTimeInMillis()));
            venta.setVendedor(ControlUserModel.getInstance().getVendedor());
            venta.setInventario(new ControlInventario().getInventario(((TableModelData.DataRegisterSell)data).getProducto()));
            ventas.add(venta);
        });
        try{
            new ControlVenta().registrarVentas(ventas);
            JOptionPane.showMessageDialog(rootPane, "Venta registrada");
            clearForm();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_botonRegisrtrarCompraActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        clearForm();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void clearForm(){
        campoCantidad.setText("");
        labelPrecio.setText("$ 0");
        labelTotalCompra.setText("$ 0");
        ((TableModelData)tablaProductos.getModel()).clearData();
        botonRegisrtrarCompra.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirProducto;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegisrtrarCompra;
    private javax.swing.JTextField campoCantidad;
    private javax.swing.JComboBox<String> comboBoxCategoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelTotalCompra;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
