/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package breadman.vista.admin.paneles.proveedor;
import breadman.logica.modelo.entidades.OrdenDeCompraInsumo;
import breadman.logica.modelo.entidades.Proveedor;
import breadman.logica.modelo.util.ComboBoxModelo;
import breadman.logica.modelo.util.FactoryCellListRenderer;
import breadman.logica.modelo.util.FactoryColumnModel;
import breadman.logica.modelo.util.TableModelData;
import breadman.logica.modelo.util.TipoDato;
import breadman.logica.modelo.util.graficas.FactoryChart;
import breadman.logica.modelo.util.graficas.TipoGrafica;
import breadman.vista.MainPanel;
import breadman.vista.SwingAttribute;
import org.jfree.chart.ChartPanel;
/**
 *
 * @author Ariel Arnedo
 */
public class PanelAdminProveedor extends MainPanel {
    
    /**
     * Creates new form PanelProveedor
     */
    public PanelAdminProveedor() {
        super();
        initComponents();
        updatePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelListProveedores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProveedores = new javax.swing.JList<>();
        jLabel1 = createLabelPrimary();
        panelMayorProveedor = new javax.swing.JPanel();
        panelProovedorData = new javax.swing.JPanel();
        panelTableOrden = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrderInsumo = new javax.swing.JTable();
        labelTitlePanelOrder = createLabelPrimary();
        panelCharDia = new javax.swing.JPanel();

        panelListProveedores.setBorder(SwingAttribute.BORDER_SECUNDARY);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        listProveedores.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        listProveedores.setModel(new ComboBoxModelo(TipoDato.PROVEEDORES)
        );
        listProveedores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listProveedores.setCellRenderer(FactoryCellListRenderer.createListCellRenderer());
        listProveedores.setSelectedIndex(0);
        listProveedores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listProveedoresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listProveedores);

        jLabel1.setText("Listado de Proveedores");

        panelMayorProveedor.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelListProveedoresLayout = new javax.swing.GroupLayout(panelListProveedores);
        panelListProveedores.setLayout(panelListProveedoresLayout);
        panelListProveedoresLayout.setHorizontalGroup(
            panelListProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListProveedoresLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(panelMayorProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelListProveedoresLayout.setVerticalGroup(
            panelListProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelMayorProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelProovedorData.setBorder(SwingAttribute.BORDER_SECUNDARY);
        panelProovedorData.setLayout(new java.awt.GridBagLayout());

        panelTableOrden.setBorder(SwingAttribute.BORDER_SECUNDARY);
        panelTableOrden.setPreferredSize(new java.awt.Dimension(0, 0));
        panelTableOrden.setLayout(new java.awt.BorderLayout());

        tableOrderInsumo.setModel(new TableModelData(OrdenDeCompraInsumo.class)
        );
        jScrollPane2.setViewportView(tableOrderInsumo);
        tableOrderInsumo.setColumnModel(FactoryColumnModel.createModelColumnTableOrdenCompraInsumo());

        panelTableOrden.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        labelTitlePanelOrder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTitlePanelOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitlePanelOrder.setText("Tabla de Insumo por Proveedor");
        labelTitlePanelOrder.setPreferredSize(new java.awt.Dimension(151, 18));
        panelTableOrden.add(labelTitlePanelOrder, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        panelProovedorData.add(panelTableOrden, gridBagConstraints);

        panelCharDia.setBorder(SwingAttribute.BORDER_SECUNDARY);
        panelCharDia.setPreferredSize(new java.awt.Dimension(0, 0));
        panelCharDia.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        panelProovedorData.add(panelCharDia, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelListProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelProovedorData, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProovedorData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelListProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listProveedoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listProveedoresValueChanged
        if(!evt.getValueIsAdjusting()){
            if(listProveedores.isSelectionEmpty())
                return;
            ComboBoxModelo comboBoxModelo = (ComboBoxModelo) listProveedores.getModel();
            Proveedor proveedor = (Proveedor) comboBoxModelo.getElementAt(listProveedores.getSelectedIndex());
            changePanelButton(new ChartPanel(FactoryChart.createPanelChartBar(proveedor, TipoGrafica.ORDENES_DIARIAS_POR_PROVEEDOR)));
            TableModelData tableModelData = (TableModelData) tableOrderInsumo.getModel();
            tableModelData.clearData();
            tableModelData.add(proveedor.getOrdenDeCompraInsumoList(), OrdenDeCompraInsumo.class);
        }
    }//GEN-LAST:event_listProveedoresValueChanged

    private void updatePanels(){
        panelMayorProveedor.add(new ChartPanel(FactoryChart.createPanelChartPie(TipoGrafica.MAYOR_PROVEEDOR)));
        if(listProveedores.getModel().getSize() != 0){
            ComboBoxModelo comboBoxModelo = (ComboBoxModelo) listProveedores.getModel();
            Proveedor proveedor = (Proveedor) comboBoxModelo.getElementAt(0);
            changePanelButton(new ChartPanel(FactoryChart.createPanelChartBar(proveedor, TipoGrafica.ORDENES_DIARIAS_POR_PROVEEDOR)));
            TableModelData tableModelData = (TableModelData) tableOrderInsumo.getModel();
            tableModelData.clearData();
            tableModelData.add(proveedor.getOrdenDeCompraInsumoList(), OrdenDeCompraInsumo.class);
        }
    }
    
    private void changePanelButton(ChartPanel panel){
        panelCharDia.removeAll();
        panelCharDia.add(panel, java.awt.BorderLayout.CENTER);
        panelCharDia.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTitlePanelOrder;
    private javax.swing.JList<String> listProveedores;
    private javax.swing.JPanel panelCharDia;
    private javax.swing.JPanel panelListProveedores;
    private javax.swing.JPanel panelMayorProveedor;
    private javax.swing.JPanel panelProovedorData;
    private javax.swing.JPanel panelTableOrden;
    private javax.swing.JTable tableOrderInsumo;
    // End of variables declaration//GEN-END:variables
}
