/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package breadman.vista.admin.paneles.inventario;

import breadman.vista.MainPanel;
import breadman.vista.SwingAttribute;

/**
 *
 * @author Ariel Arnedo
 */
public class PanelAdminInventario extends MainPanel {
    
    /**
     * Creates new form PanelInventario
     */
    public PanelAdminInventario() {
        super();
        initComponents();
        updatePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAction = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonInventarioProducto = createButtonMenu();
        botonInventarioInsumo = createButtonMenu();
        jSeparator2 = new javax.swing.JSeparator();
        botonInventarioVentaDeProducto = createButtonMenu();
        jSeparator3 = new javax.swing.JSeparator();
        botonInventarioCapacidad = createButtonMenu();
        panelCenter = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(185, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INVENTARIO");

        jSeparator1.setForeground(new java.awt.Color(102, 204, 255));

        botonInventarioProducto.setText("Productos");
        botonInventarioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioProductoActionPerformed(evt);
            }
        });

        botonInventarioInsumo.setText("Insumos");
        botonInventarioInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioInsumoActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botonInventarioVentaDeProducto.setText("Ventas de Productos");
        botonInventarioVentaDeProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioVentaDeProductoActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botonInventarioCapacidad.setText("Capacidad del Inventario");
        botonInventarioCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioCapacidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActionLayout = new javax.swing.GroupLayout(panelAction);
        panelAction.setLayout(panelActionLayout);
        panelActionLayout.setHorizontalGroup(
            panelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addGroup(panelActionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(panelActionLayout.createSequentialGroup()
                        .addComponent(botonInventarioProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonInventarioInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonInventarioVentaDeProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonInventarioCapacidad)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelActionLayout.setVerticalGroup(
            panelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(panelActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonInventarioProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonInventarioVentaDeProducto))
                    .addComponent(jSeparator2)
                    .addComponent(botonInventarioInsumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActionLayout.createSequentialGroup()
                        .addComponent(botonInventarioCapacidad)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        add(panelAction, java.awt.BorderLayout.NORTH);

        panelCenter.setBorder(SwingAttribute.BORDER_MAIN);
        panelCenter.setLayout(new java.awt.BorderLayout());
        setPanelWorking(panelCenter);
        add(panelCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void updatePanels(){
        changePanel(new PanelInventarioProducto());
    }
    
    private void botonInventarioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioProductoActionPerformed
        changePanel(new PanelInventarioProducto());
    }//GEN-LAST:event_botonInventarioProductoActionPerformed

    private void botonInventarioVentaDeProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioVentaDeProductoActionPerformed
        changePanel(new PanelInventarioVenta());
    }//GEN-LAST:event_botonInventarioVentaDeProductoActionPerformed

    private void botonInventarioCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioCapacidadActionPerformed
        changePanel(new PanelInventarioCapacidad());
    }//GEN-LAST:event_botonInventarioCapacidadActionPerformed

    private void botonInventarioInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioInsumoActionPerformed
        changePanel(new PanelInventarioInsumo());
    }//GEN-LAST:event_botonInventarioInsumoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInventarioCapacidad;
    private javax.swing.JButton botonInventarioInsumo;
    private javax.swing.JButton botonInventarioProducto;
    private javax.swing.JButton botonInventarioVentaDeProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelAction;
    private javax.swing.JPanel panelCenter;
    // End of variables declaration//GEN-END:variables
}
