/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package breadman.vista.admin.paneles.inventario;

import breadman.logica.modelo.util.graficas.FactoryChart;
import breadman.logica.modelo.util.graficas.TipoGrafica;
import breadman.vista.MainPanel;
import breadman.vista.SwingAttribute;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author Ariel Arnedo
 */
public class PanelInventarioVenta extends MainPanel {

    
    /**
     * Creates new form PanelInventarioVenta
     */
    public PanelInventarioVenta() {
        super();
        initComponents();
        updatePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelVentasDiaria = new javax.swing.JPanel();
        panelProductosMasVendidos = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        panelVentasDiaria.setBorder(SwingAttribute.BORDER_SECUNDARY);
        panelVentasDiaria.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        add(panelVentasDiaria, gridBagConstraints);

        panelProductosMasVendidos.setBorder(SwingAttribute.BORDER_SECUNDARY);
        panelProductosMasVendidos.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        add(panelProductosMasVendidos, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void updatePanels(){
        panelVentasDiaria.add(new ChartPanel(FactoryChart.createPanelChartBar(TipoGrafica.VENTAS_POR_DIA)));
        panelProductosMasVendidos.add(new ChartPanel(FactoryChart.createPanelChartBar(TipoGrafica.PRODUCTOS_MAS_VENDIDOS)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelProductosMasVendidos;
    private javax.swing.JPanel panelVentasDiaria;
    // End of variables declaration//GEN-END:variables
}
