/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package breadman.vista.admin.paneles.inventario;
import breadman.logica.modelo.util.graficas.FactoryChart;
import breadman.logica.modelo.util.graficas.TipoGrafica;
import breadman.vista.MainPanel;
import breadman.vista.SwingAttribute;
import org.jfree.chart.ChartPanel;
/**
 *
 * @author Ariel Arnedo
 */
public class PanelInventarioCapacidad extends MainPanel  {

    /**
     * Creates new form PanelCapacidadInventario
     */
    public PanelInventarioCapacidad() {
        super();
        initComponents();
        updatePanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCenter = new javax.swing.JPanel();

        panelCenter.setBorder(SwingAttribute.BORDER_SECUNDARY);
        panelCenter.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatePanels(){
        panelCenter.add(new ChartPanel(FactoryChart.createPanelChartPie(TipoGrafica.CAPACIDAD_DE_INVENTARIO)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelCenter;
    // End of variables declaration//GEN-END:variables
}
