/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package breadman.vista.produccion.paneles;
import breadman.logica.modelo.core.ControlUserModel;
import breadman.logica.modelo.entidades.Lote;
import breadman.logica.modelo.entidades.OrdenProduccion;
import breadman.logica.modelo.persistencia.daos.ControlLote;
import breadman.logica.modelo.persistencia.daos.ControlOrdenProduccion;
import breadman.logica.modelo.persistencia.daos.ControlProducto;
import breadman.vista.MainFrame;
import breadman.vista.MainPanel;
import breadman.vista.SwingAttribute;
import java.text.DateFormat;
import java.time.format.DateTimeFormatter;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.JOptionPane;
/**
 *
 * @author Ariel Arnedo
 */
public class PanelProduccionLote extends MainPanel{

    private OrdenProduccion produccion_a_registrar = null;
    /**
     * Creates new form PanelRegistrarLote
     */
    public PanelProduccionLote() {
        super();
        initComponents();
        updateForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = createLabelSecundary();
        campoProducto = createTextField();
        campoFechaPrevista = createTextField();
        campoCantidad = createTextFieldNumeric();
        jLabel2 = createLabelSecundary();
        jLabel3 = createLabelSecundary();
        jButton1 = createButtonSecondary();
        botonRegistarLote = createButtonSecondary();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoAreaOrdenActuales = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoAreaOrdenPendientes = new javax.swing.JTextArea();

        jPanel1.setBorder(SwingAttribute.BORDER_MAIN);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel1.setText("Producto en Producción");

        campoProducto.setEditable(false);

        campoFechaPrevista.setEditable(false);

        campoCantidad.setEditable(false);

        jLabel2.setText("Fecha prevista para la orden de produccion");

        jLabel3.setText("Cantidad a producir");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoProducto)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoFechaPrevista)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(campoCantidad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(campoFechaPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        botonRegistarLote.setText("Registrar Lote");
        botonRegistarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistarLoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonRegistarLote, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botonRegistarLote)
                .addContainerGap())
        );

        botonRegistarLote.setEnabled(new ControlOrdenProduccion().cantidadOrdenesActuales() != 0);

        jPanel2.setBorder(SwingAttribute.BORDER_MAIN);
        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel2.setMinimumSize(new java.awt.Dimension(182, 364));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        textoAreaOrdenActuales.setEditable(false);
        textoAreaOrdenActuales.setColumns(10);
        textoAreaOrdenActuales.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        textoAreaOrdenActuales.setForeground(new java.awt.Color(102, 102, 102));
        textoAreaOrdenActuales.setLineWrap(true);
        textoAreaOrdenActuales.setRows(8);
        textoAreaOrdenActuales.setTabSize(1);
        textoAreaOrdenActuales.setText("Actualmente tiene "+new ControlOrdenProduccion().cantidadOrdenesActuales()+" ordenes de producción para el día de hoy");
        textoAreaOrdenActuales.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textoAreaOrdenActuales);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        jPanel2.add(jScrollPane1, gridBagConstraints);
        jScrollPane1.getAccessibleContext().setAccessibleName("");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        textoAreaOrdenPendientes.setEditable(false);
        textoAreaOrdenPendientes.setColumns(10);
        textoAreaOrdenPendientes.setFont(textoAreaOrdenActuales.getFont());
        textoAreaOrdenPendientes.setForeground(textoAreaOrdenActuales.getForeground());
        textoAreaOrdenPendientes.setLineWrap(true);
        textoAreaOrdenPendientes.setRows(5);
        textoAreaOrdenPendientes.setText("Actualmente tiene "+new ControlOrdenProduccion().cantidadOrdenesPendientes()+" ordenes de producción pendientes");
        textoAreaOrdenPendientes.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textoAreaOrdenPendientes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        jPanel2.add(jScrollPane2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistarLoteActionPerformed
        if(campoCantidad.isEditable() && campoCantidad.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(campoProducto, "No puede registrar un lote sin especificar la cantidad producidas");
            return;
        }        
        
        Lote lote = new Lote();
        lote.setCantidadProducida(Integer.parseInt(campoCantidad.getText()));
        lote.setIdCodigoOrdenProduccion(produccion_a_registrar);
        lote.setInventario(produccion_a_registrar.getIdProducto().getInventarioList().get(0));
        lote.setPanadero(ControlUserModel.getInstance().getPanadero());
        lote.setFechaDeProduccion(produccion_a_registrar.getFechaPrevista());
        
        ControlLote controlLote = new ControlLote();
        
        try{
            controlLote.addLote(lote);
            JOptionPane.showMessageDialog(this, "Lote Registrado");
            updateFields();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_botonRegistarLoteActionPerformed

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        campoCantidad.setEditable(true);
        campoCantidad.setBorder(SwingAttribute.BORDER_MAIN);
        campoCantidad.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateFields(){
        textoAreaOrdenActuales.setText("Actualmente tiene "+new ControlOrdenProduccion().cantidadOrdenesActuales()+" ordenes de producción para el día de hoy");
        textoAreaOrdenPendientes.setText("Actualmente tiene "+new ControlOrdenProduccion().cantidadOrdenesPendientes()+" ordenes de producción pendientes");
        campoProducto.setText("");
        campoFechaPrevista.setText("");
        campoCantidad.setEditable(false);
        campoCantidad.setText("");
    }
    
    private void updateForm(){
        produccion_a_registrar = new ControlOrdenProduccion().getProduccionMasReciente();
        if(produccion_a_registrar == null)
            return;
        
        campoProducto.setText(produccion_a_registrar.getIdProducto().getNombre());
        GregorianCalendar calendar = new GregorianCalendar();
        calendar.setTimeInMillis(produccion_a_registrar.getFechaPrevista().getTime());
        campoFechaPrevista.setText(calendar.get(GregorianCalendar.DAY_OF_MONTH)+"/"+calendar.get(GregorianCalendar.MONTH)+"/"+calendar.get(GregorianCalendar.YEAR));
        campoCantidad.setText(produccion_a_registrar.getCantidad()+"");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistarLote;
    private javax.swing.JTextField campoCantidad;
    private javax.swing.JTextField campoFechaPrevista;
    private javax.swing.JTextField campoProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textoAreaOrdenActuales;
    private javax.swing.JTextArea textoAreaOrdenPendientes;
    // End of variables declaration//GEN-END:variables
}
